### ISSUE TITLE
Running ginsta user_info causes ginsta to crash

### ISSUE THREAD

**Issue by Krishna** [gedex/ginsta#3]
<pre>
$ ginsta user_info rawvana
Error: %!v(PANIC=runtime error: invalid memory address or nil pointer dereference)
$go version  
go version go1.4 darwin/amd64
</pre>

**Comment by gedex** [comment]
I've fixed relevant error from [go-instagram](https://github.com/gedex/go-instagram) package. Please do `go get -u github.com/gedex/ginsta`. Also, `ginsta user_info` expects user ID instead of username. You can get user ID from `ginsta search_user rawvana`.

**Comment by Krishna** [comment]
Great! Thank you for the fix and all your work on the ginsta client and go-instagram package.
