### ISSUE TITLE
Client seems to be in sandbox mode

### ISSUE THREAD

**Issue by ghost** [gedex/ginsta#5]
When attempting to authorize this client and get an `access_token`, I received this response:

```
{"code": 403, "error_type": "OAuthForbiddenException", "error_message": "You are not a sandbox user of this client"}
```

It appears that the client (which looks very promising, by the way) is still in sandbox mode, so I can't authorize it. What can be done about this? Could you submit the client for review?

**Comment by gedex** [comment]
@sirbiden I think `ginsta` won't adhere their [platform policy](https://www.instagram.com/about/legal/terms/api/), not sure though. But their guideline says not to use 'insta' on app name.

For now, you can create your own client from https://www.instagram.com/developer/clients/manage/ and then specify `-client-id`:

```
ginsta token_get [-client-id CLIENT_ID] [-scope SCOPE]
```
